Ensign:
  prefix: '&9&lEnsign '
  cost: 0.00
  priority: 0
Corporal:
  prefix: '&2&lCorporal '
  cost: 10000.00
  priority: 1
Sergeant:
  prefix: '&a&lSergeant '
  cost: 30000.00
  priority: 2
Chief:
  prefix: '&e&lChief '
  cost: 90000.00
  priority: 3
Veteran:
  prefix: '&6&lVeteran '
  cost: 270000.00
  priority: 4