Ensign:
  prefix: '&9&lEnsign '
  cost: 0
  default: true
Corporal:
  prefix: '&2&lCorporal '
  cost: 10000
  default: false
Sergeant:
  prefix: '&a&lSergeant '
  cost: 30000
  default: false
Chief:
  prefix: '&e&lChief '
  cost: 90000
  default: false
Veteran:
  prefix: '&6&lVeteran '
  cost: 270000
  default: false