Ensign:
  prefix: '&9&lEnsign '
  cost: 0.00
  default: true
Corporal:
  prefix: '&2&lCorporal '
  cost: 10000.00
  default: false
Sergeant:
  prefix: '&a&lSergeant '
  cost: 30000.00
  default: false
Chief:
  prefix: '&e&lChief '
  cost: 90000.00
  default: false
Veteran:
  prefix: '&6&lVeteran '
  cost: 270000.00
  default: false