main: me.brownie.galacticcraftranks.GalacticCraftRanks
name: GalacticCraftRanks
author: NoahBrown2015
version: 1.1
api-version: 1.15
depend: [ Vault ]

commands:
  ranks:
    description: Displays all ranks and their prices
    usage: /<command>
  rankup:
    description: Purchase the next rank
    usage: /<command>