main: me.brownie.galacticraftranks.GalacticraftRanks
name: GalacticraftRanks
author: NoahBrown2015
version: 1.0
api-version: 1.15

commands:
  ranks:
    description: Displays all ranks and their prices
    usage: /<command>
  rankup:
    description: Purchase the next rank
    usage: /<command>